server:
  auth:
    redirect-ip: http://localhost:3000/

spring:
  datasource:
    url: jdbc:postgresql://49.233.4.79:30432/test?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

kubernetes:
  persistent-volume-claim:
    docsify-data-volume: E:\\
    nginx-static-data-volume: E:\\app\\data

BaiDu:
  AppID: 27103657
  AppKey: BIukdHDXeNPmIXe96GA6OOXGgnP5GEhM
  SecretKey: rFnbg0rnz41UOrSGkGZ0hOISku0sqDOc
  RedirectUri: http://localhost:8080/auth/api/v1/authorize/baidu
  Scope: basic
  AuthorizeUri: http://openapi.baidu.com/oauth/2.0/authorize
  QrCode: 1
  AccessToken: https://openapi.baidu.com/oauth/2.0/token

violin:
  redis:
    # we use database 3
    database: 3
    host: localhost
    port: 6379
    password: 123456
    timeout: 0
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: -1

logging:
  config: classpath:logback-spring-dev.xml