server:
  auth:
    redirect-ip: http://www.violin-home.cn/
  mongo:
    service: 127.0.0.1
spring:
  datasource:
    url: jdbc:mysql://violin-mysql:3306/violin?allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    initialization-mode: always
  data:
    mongodb:
      uri: mongodb://mongo:27017/violin
      transactionEnabled: true